### ISSUE TITLE
Add the ability to find js overwrites

### ISSUE THREAD

**Issue by digitalpianism** [experius/Magento-1-Experius-Patch-Helper#8]
For example, SUPEE 9767 adds some changes to the opcheckout.js file, it'd be great to add the possibility to find out if that file is being overriden in the custom theme.

So I'd say primarily /skin JS files

**Comment by lewisvoncken** [comment]
Hello @digitalpianism 

This is already solved in the latest version and in a previous issue https://github.com/experius/Magento-1-Experius-Patch-Helper/issues/6

in release 1.0.4 https://github.com/experius/Magento-1-Experius-Patch-Helper/releases/tag/1.0.4

**Comment by digitalpianism** [comment]
Haha well done, I was running a version downloaded last week ^^
